Http4 s transaction changes
newrelic/newrelic-java-agent pull request #1006
Opened 2022-09-09 21:45 UTC by richard-gibson

_Before contributing, please read our [contributing guidelines](https://github.com/newrelic/newrelic-java-agent/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/newrelic/.github/blob/main/CODE_OF_CONDUCT.md)._

### Overview
Describe the changes present in the pull request

### Related Github Issue
Include a link to the related GitHub issue, if applicable

### Testing
The agent includes a suite of tests which should be used to
verify your changes don't break existing functionality. These tests will run with
Github Actions when a pull request is made. More details on running the tests locally can be found
[here](https://github.com/newrelic/newrelic-java-agent/blob/main/CONTRIBUTING.md),

### Checks

[ ] Are your contributions backwards compatible with relevant frameworks and APIs?
[ ] Does your code contain any breaking changes? Please describe. 
[ ] Does your code introduce any new dependencies? Please describe.

2022-09-23 21:48 UTC, meiao requested changes

2022-09-23 21:48 UTC, meiao commented on instrumentation/cats-effect-3.3.0/src/main/scala/cats/effect/IOFiber_Instrumentation.scala
> +  def run(): Unit = {
can you add a line between these functions?
reading thru this and getting confused by which is the function for this body.

2022-09-23 21:48 UTC, meiao commented on instrumentation/cats-effect-3.3.0/src/main/scala/cats/effect/IOFiber_Instrumentation.scala
> +        }
the 2nd if statement is redundant

2022-09-23 21:48 UTC, meiao commented on instrumentation/cats-effect-3.3.0/src/main/scala/cats/effect/IOFiber_Instrumentation.scala
> +        incrementTokenRefCount(this.tokenAndRefCount.get())
Is the Weaver.callOriginal() running async and the decrement in done the reverse of this increment?

2022-09-26 13:13 UTC, richard-gibson commented on instrumentation/cats-effect-2/src/main/scala/cats/effect/ec/TokenAwareExecutionContext.scala
> +  override def reportFailure(cause: Throwable): Unit = delegate.reportFailure(cause)
Yes, I think so, we don't want to lose any custom reportFailure that could be specified by a user in the delegate Execution context

2022-09-26 13:15 UTC, meiao commented on instrumentation/cats-effect-2/src/main/scala/cats/effect/ec/TokenAwareExecutionContext.scala
> +  override def reportFailure(cause: Throwable): Unit = delegate.reportFailure(cause)
Nevermind, I was really tired at this point and missed that there is a TokenAwareRunnable in there.

2022-09-26 21:50 UTC, meiao commented on instrumentation/http4s-ember-client-2.13_0.23/src/main/scala/com/nr/instrumentation/http4s/NewrelicClientMiddleware.scala
> +        response <- client.run(req)
Won't these run async?

2022-09-26 21:50 UTC, meiao commented on instrumentation/http4s-ember-server-2.12_0.23/src/main/java/org/http4s/server/blaze/EmberServerBuilder_Instrumentation.java
> +package org.http4s.server.blaze;
Wrong package

2022-09-26 21:50 UTC, meiao commented on settings.gradle
> +include 'instrumentation:cats-effect-3.2'
Probably already fixed, but cats-effect-3 is missing.

2022-09-27 14:07 UTC, meiao approved these changes

2022-09-27 15:01 UTC, merged