update changelog for 6.2.0
newrelic/newrelic-java-agent pull request #107
Opened 2020-11-09 21:49 UTC by gfuller1

Changelog update for 6.2.0 release.

2020-11-09 22:33 UTC, jodeev commented on CHANGELOG.md
> +
Insert a new statement to add limits to supported versions:

### Support statement:
```suggestion
```suggestion
### Support statement:
* New Relic recommends that you upgrade the agent regularly and at a minimum every 3 months. As of this release, the oldest supported version is [5.9.0](https://docs.newrelic.com/docs/release-notes/agent-release-notes/java-release-notes/java-agent-590).
```
```

2020-11-09 22:37 UTC, jodeev requested changes
LGTM, just add the new support statement at the bottom. This will be included with each new release, adjusting the last supported version to be the oldest version less than two years old.

2020-11-10 18:01 UTC, jasonjkeller approved these changes

2020-11-10 19:15 UTC, jasonjkeller approved these changes
LGTM

2020-11-10 19:19 UTC, merged