Add ZIO 2 support
newrelic/newrelic-java-agent pull request #1106
Opened 2022-12-29 08:48 UTC by duartesaraiva98

### Overview
Adding instrumentation for ZIO 2 to the agent. Currently there is only instrumentation for ZIO 1 which is not compatible with ZIO 2. The majority of this code is based on ZIO 1 implementation with some slight changes to make it work.

### Related Github Issue
-

### Checks

[Yes ] Are your contributions backwards compatible with relevant frameworks and APIs?
[ No] Does your code contain any breaking changes? Please describe. 
[ No] Does your code introduce any new dependencies? Please describe.

2022-12-29 08:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-java-agent?pullRequest=1106) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-java-agent?pullRequest=1106) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Duarte Saraiva<br/>:x: jmast-zorgdomein<br/><hr/>**Duarte Saraiva** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-java-agent?pullRequest=1106) it.</sub>

2023-01-04 09:59 UTC, duartesaraiva98 commented
@tbradellis Is this something you could take a look at? You added instrumentation for ZIO 1, right?

2023-01-10 15:04 UTC, kford-newrelic commented
@duartesaraiva98 thanks for the PR!

We've got a fair bit of work on our board at the moment but we'll review this as soon as possible

2023-02-14 02:06 UTC, kford-newrelic commented
@duartesaraiva98 apologies but we had to bump this out to the Apr-Jun quarter - we're over-capacity for the current quarter

2023-05-25 13:16 UTC, tbradellis requested changes

2023-05-25 13:16 UTC, tbradellis commented on instrumentation/zio-2/src/main/java/zio/TokenAwareRunnable.java
@duartesaraiva98 
Sorry for the delay on getting this reviewed.  I'd like to get it into main this week for our upcoming release. 
It looks like this group of 4 classes in `zio` are duplicates of the correct ones in `zio.internal`.
Do you want to push a change to delete those to this PR? Or, I can make the change where I pulled your commits in here for testing:
https://github.com/newrelic/newrelic-java-agent/pull/1144
Whatever works for you.

2023-05-25 15:21 UTC, tbradellis commented on newrelic-scala-zio-2-api/src/test/scala/com/newrelic/zio/api/TraceOpsDSLTest.scala
> +  def asyncTraceProducesOneSegment(): Unit = {
All 6 unit tests seem to be failing.
https://github.com/newrelic/newrelic-java-agent/actions/runs/5079780519/jobs/9128030914?pr=1144

2023-05-26 22:12 UTC, tbradellis commented on newrelic-scala-zio-2-api/src/test/scala/com/newrelic/zio/api/TraceOpsDSLTest.scala
> +  def asyncTraceProducesOneSegment(): Unit = {
I believe I have this resolved. Running tests now. These need to be run in a separate workflow as functional tests.

2023-05-31 13:37 UTC, tbradellis commented on newrelic-scala-zio-2-api/src/test/scala/com/newrelic/zio/api/TraceOpsDSLTest.scala
> +  def asyncTraceProducesOneSegment(): Unit = {
@duartesaraiva98 I was able to resolve the testing issues.
My changes are here:
https://github.com/newrelic/newrelic-java-agent/pull/1144/files

However, testing the instrumentation locally with restful webservices in:
https://github.com/zio/zio-quickstarts
 I can see the module loads, but we lose the Transaction context and only report `NettyDispatcher` and don't see the underlying traces for the route.
 I saw this on 2.0.13; scala 2.13.8, and Java 11.

2023-07-17 19:10 UTC, tbradellis commented
We are closing this for now, because we are not able to get it on the roadmap to investigate the issue with losing Transaction context described in the comment [here](https://github.com/newrelic/newrelic-java-agent/pull/1106#discussion_r1211734129).

Feel free to resubmit with that addressed and we can likely get it merged.  Tests were otherwise passing for the PR.

2023-09-08 11:23 UTC, kford-newrelic commented
Reviewing for possible further action in the oct-dec quarter

2023-09-11 14:47 UTC, kford-newrelic commented
Not able to address fixing the lost transaction issue in the coming oct-dec quarter. Will consider again for the following quarter.

2023-10-27 09:10 UTC, closed without merging

2023-11-06 19:56 UTC, jasonjkeller commented
Here's another repro app, this one from [NR-175811](https://new-relic.atlassian.net/browse/NR-175811) using ZIO 1.x:
[NewrelicTestProject.zip](https://github.com/newrelic/newrelic-java-agent/files/13271941/NewrelicTestProject.zip)