NR-64056 Error grouping
newrelic/newrelic-java-agent pull request #1195
Opened 2023-04-03 17:06 UTC by jtduffy

Implements the error grouping feature:
- Callback handler and error data classes
- API upgrade for callback registration
- Callback invoked for each error reported to NR
- Javadocs
- Associated unit tests

2023-04-03 17:12 UTC, obenkenobi commented on newrelic-agent/src/main/java/com/newrelic/api/agent/NewRelicApiImplementation.java
> +        ErrorGroupCallbackHolder.setErrorGroupCallback((errorGroupCallback));
Double parentheses?

2023-04-03 17:13 UTC, jtduffy commented on newrelic-agent/src/main/java/com/newrelic/api/agent/NewRelicApiImplementation.java
> +        ErrorGroupCallbackHolder.setErrorGroupCallback((errorGroupCallback));
lol oops

2023-04-03 17:17 UTC, obenkenobi commented on newrelic-api/src/main/java/com/newrelic/api/agent/NewRelic.java
> +    public static void setErrorGroupCallback(ErrorGroupCallback errorGroupCallback){
Where is the `@since` comment section other methods have?

2023-04-03 17:24 UTC, obenkenobi commented on newrelic-agent/src/main/java/com/newrelic/agent/errors/ErrorDataImpl.java
> +        return transactionData != null ? transactionData.getAgentAttributes().get(AttributeNames.REQUEST_URI).toString() : "";
What would happen if `transactionData.getAgentAttributes().get(AttributeNames.REQUEST_URI)` returns null?

2023-04-03 17:27 UTC, obenkenobi commented on newrelic-agent/src/main/java/com/newrelic/agent/errors/ErrorDataImpl.java
> +        return transactionData != null ? transactionData.getAgentAttributes().get(AttributeNames.HTTP_STATUS_CODE).toString() : "";
Does `transactionData.getAgentAttributes().get(AttributeNames. HTTP_STATUS_CODE)` ever return null? If it does return null, maybe add a default empty string value?

2023-04-03 17:28 UTC, obenkenobi commented on newrelic-agent/src/main/java/com/newrelic/agent/errors/ErrorDataImpl.java
> +        return transactionData != null ? transactionData.getAgentAttributes().get(AttributeNames.REQUEST_METHOD_PARAMETER_NAME).toString() : "";
Does `transactionData.getAgentAttributes().get(AttributeNames. REQUEST_METHOD_PARAMETER_NAME)` ever return null? If it does return null, maybe add a default empty string value?

2023-04-03 17:31 UTC, obenkenobi commented on newrelic-agent/src/main/java/com/newrelic/agent/errors/ErrorDataImpl.java
> +        return (tracedError != null && tracedError instanceof ThrowableError);
redundant parentheses?

2023-04-03 17:31 UTC, obenkenobi commented on newrelic-agent/src/main/java/com/newrelic/agent/errors/ErrorDataImpl.java
> +        return (transactionData != null && transactionData.getThrowable() != null);
redundant parentheses?

2023-04-03 17:46 UTC, obenkenobi requested changes
Overall this looks good. There are some NPE risks and minor code style comments I'd like to be addressed beforehand.

2023-04-03 17:53 UTC, obenkenobi commented on newrelic-agent/src/test/java/com/newrelic/agent/errors/ErrorDataImplTest.java
> +public class ErrorDataImplTest {
It is a good idea to add tests for when we are in a non-web transaction and you call `getRequestUri `, `getHttpStatusCode `, and `getHttpMethod ` where we expect to return empty string. I suspect the current implementation as of this commit risks a `NullPointerException`.

2023-04-03 20:15 UTC, meiao commented on newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/ErrorEventFactory.java
> +            Agent.LOG.warning(MessageFormat.format("Customer errorGroupCallback implementation threw an exception: {0}", e.getMessage()));
Can we add a message with the stack trace for finest level logs?

2023-04-03 20:15 UTC, meiao commented on newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/ErrorEventFactory.java
> +            Agent.LOG.warning(MessageFormat.format("Customer errorGroupCallback implementation threw an exception: {0}", e.getMessage()));
Also note that the MessageFormat.format is executed even if the log is set to SEVERE only.

2023-04-03 20:15 UTC, meiao commented on newrelic-api/src/main/java/com/newrelic/api/agent/ErrorGroupCallback.java
> + * grouping key from being assigned. Note that all the methods in ErrorData will never return null, just empty Strings or
getException is an exception to this affirmation.

2023-04-04 17:11 UTC, obenkenobi approved these changes

2023-04-05 18:34 UTC, meiao approved these changes

2023-04-06 18:29 UTC, meiao approved these changes

2023-04-06 19:32 UTC, merged