NR-55012 Java 20 support
newrelic/newrelic-java-agent pull request #1226
Opened 2023-04-27 14:12 UTC by jtduffy

- Update ASM version
- Update supported version regex, tests, etc
- Update GHA workflows for java 20
- Addition of `Java20IncompatibleTest` marker interface; removed `Java19IncompatibleTest` interface

2023-04-27 14:28 UTC, meiao requested changes

2023-04-27 14:28 UTC, meiao commented on .github/workflows/GHA-Functional-Tests.yaml
> +          s|jdk20=20|jdk20=${ORG_GRADLE_PROJECT_jdk20}|" gradle.properties.gha
There are a few places that we set a envvar GRADLE_PROPERTIES, and the ORG_GRADLE_PROJECT_jdk19 should be changed there also.

2023-04-28 01:58 UTC, meiao approved these changes

2023-04-28 07:19 UTC, tbradellis approved these changes

2023-04-28 16:31 UTC, merged