Add local decorating for customers using Log4j 2 with JsonTemplateLayout
newrelic/newrelic-java-agent pull request #1866
Opened 2024-04-18 21:29 UTC by obenkenobi

### Overview
Adds local decorating (i.e. NR-LINKING metadata) to log4j 2 logs using `JsonTemplateLayout` such as shown configured in the XML snippet below:

```xml
	<Appenders>
		<Console name="Console" target="SYSTEM_OUT">
			
                         <JsonTemplateLayout eventTemplateUri="classpath:JsonLayout.json"/>
		</Console>
	</Appenders>
```

Example log without local decorating:
```json
{
  "@timestamp": "2024-04-18T21:08:01.250Z",
  "log.level": "INFO",
  "process.thread.name": "http-nio-8081-exec-1",
  "log.logger": "org.springframework.samples.petclinic.system.WelcomeController",
  "message": "info bar"
}
```
Example log with local decorating:
```json
{
  "@timestamp": "2024-04-18T21:08:01.250Z",
  "log.level": "INFO",
  "process.thread.name": "http-nio-8081-exec-1",
  "log.logger": "org.springframework.samples.petclinic.system.WelcomeController",
  "message": "info bar NR-LINKING|MzQ3Nzg3NHxBUE18QVBQTElDQVRJT058NTM4Mzc3ODY0|192.168.0.31|e0a726b1de7a78af9e74bfb042845180|3f4885dca4f83070|Petclinic+Log4j+Jsontemplatelayout+decorating|"
}
```

### Related Github Issue
[#1730](https://github.com/newrelic/newrelic-java-agent/issues/1730)

2024-04-18 22:25 UTC, jasonjkeller requested changes
Couple of minor tweaks to be made but otherwise looks good.

2024-04-19 15:11 UTC, obenkenobi commented on agent-bridge/src/main/java/com/newrelic/agent/bridge/logging/Log4jUtils.java
> +package com.newrelic.agent.bridge.logging;
Added the headers

2024-04-19 15:12 UTC, obenkenobi commented on instrumentation/apache-log4j-layout-template-json-2.14.0/Readme.md
> +        <!-- THIS DOES NOT WORK! Use JsonTemplateLayout with default JsonLayout provided by log4j2 -->
Updated the readme

2024-04-23 21:51 UTC, jasonjkeller approved these changes

2024-04-24 14:34 UTC, merged