Move init container release from lambda to GHA
newrelic/newrelic-java-agent pull request #2179
Opened 2024-12-18 23:40 UTC by hmstepanek

### Overview
We are getting rid of the internal auto-layer-releases repo and moving creating of the release tags into each agent's GHA deploy flow.

2025-01-28 23:11 UTC, kanderson250 requested changes
I think we should move this into its own workflow, to be run at the end of our release process.

I'm not super familiar with the init container process, but it looks like these changes will cut the init container release immediately. `publish_release` is the start of our release process. The agent jar generally isn't available on the downloads site, where the init container is [looking for it]( https://github.com/newrelic/newrelic-agent-init-container/blob/ea17827b41bb1609c6f53b8055508d6f684193f8/src/java/java-agent-download.sh#L12), until a few days after this action is run.

2025-01-29 01:27 UTC, kanderson250 requested changes

2025-01-29 01:27 UTC, kanderson250 commented on .github/workflows/Create-Release-Tags.yml
> +        default: 'main'
We shouldn't need to check out the agent itself for this. We just need a version number. 
```suggestion
      agent-version:
        description: 'The release tag to create init containers for, including the v. Eg v8.12.0’. '
        required: true
```

2025-01-29 01:27 UTC, kanderson250 commented on .github/workflows/Create-Release-Tags.yml
> +          ref: ${{ inputs.agent-ref }}
don't need to checkout the agent repo for this
```suggestion
```

2025-01-29 01:27 UTC, kanderson250 commented on .github/workflows/Create-Release-Tags.yml
> +          RELEASE_NOTES="Automated release for [Java Agent ${GITHUB_REF}](https://github.com/newrelic/newrelic-java-agent/releases/tag/${GITHUB_REF})"
As far as I know, `GITHUB_REF` doesn't exist for manually triggered builds. Replace with `inputs.agent-version`. 
```suggestion
          RELEASE_TITLE="New Relic Java Agent ${inputs.agent-version}.0"
          RELEASE_TAG="${inputs.agent-version}.0_java"
          RELEASE_NOTES="Automated release for [Java Agent ${inputs.agent-version}](https://github.com/newrelic/newrelic-java-agent/releases/tag/${inputs.agent-version})"
```

2025-01-29 18:38 UTC, hmstepanek commented on .github/workflows/Create-Release-Tags.yml
> +          RELEASE_TITLE="New Relic Java Agent ${{ inputs.agent-ref }}.0"
```suggestion
          RELEASE_TITLE="New Relic Java Agent ${{ inputs.agent-version }}.0"
```

2025-01-29 18:38 UTC, hmstepanek commented on .github/workflows/Create-Release-Tags.yml
> +          RELEASE_TAG="${{ inputs.agent-ref }}.0_java"
```suggestion
          RELEASE_TAG="${{ inputs.agent-version }}.0_java"
```

2025-01-29 18:38 UTC, hmstepanek commented on .github/workflows/Create-Release-Tags.yml
> +          RELEASE_NOTES="Automated release for [Java Agent ${{ inputs.agent-ref }}](https://github.com/newrelic/newrelic-java-agent/releases/tag/${{ inputs.agent-ref }})"
```suggestion
          RELEASE_NOTES="Automated release for [Java Agent ${{ inputs.agent-version }}](https://github.com/newrelic/newrelic-java-agent/releases/tag/${{ inputs.agent-version }})"
```

2025-01-29 18:50 UTC, kanderson250 approved these changes
Looks good, thank you! Will merge myself once release activities conclude this week.

2025-01-30 18:39 UTC, jtduffy commented
Merging with AIT failures (token issue). New workflow action that AITs don't cover.

2025-01-30 18:39 UTC, merged