XML extensions to mirror class annotations trace lambda and trace by return type behaviour
newrelic/newrelic-java-agent pull request #288
Opened 2021-04-30 08:54 UTC by GDownes

### Overview
Describe the changes present in the pull request

### Testing
Unit tests addded
Local testing

### Checks

[X] Are your contributions backwards compatible with relevant frameworks and APIs? Yes
[X] Does your code contain any breaking changes? Please describe. No
[X] Does your code introduce any new dependencies? Please describe. No

2021-06-22 19:18 UTC, meiao requested changes

2021-06-23 09:14 UTC, GDownes commented on newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/methodmatchers/LambdaMethodMatcher.java
> +        return (includeNonstatic || access == 4121 || access == Opcodes.F_NEW) && lambdaMethodPattern.matcher(name).matches();
Added constant ACCESS_SYNTHETIC_STATIC to class for int 4121

2021-06-23 09:14 UTC, GDownes commented on newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/methodmatchers/LambdaMethodMatcher.java
> +    private final Boolean includeNonstatic;
Updated to boolean

2021-06-23 09:15 UTC, GDownes commented on newrelic-agent/src/main/java/com/newrelic/agent/extension/beans/Extension.java
> +            public void setIncludeNonstatic(Boolean value) {
Updated to boolean

2021-06-23 13:47 UTC, meiao approved these changes

2021-06-24 15:37 UTC, meiao commented
AITs green on https://javaagent-build.pdx.vm.datanerd.us/job/JavaAgent_PR_AIT/96/

2021-06-24 16:00 UTC, merged