feat: add log4j-1 metrics instrumentation
newrelic/newrelic-java-agent pull request #673
Opened 2022-01-21 12:19 UTC by danybmx

### Overview
This PR continues the work done on #618 and #668 and adds instrumentation metrics to log4j-1.x

### Related Github Issue
N/A

### Testing
Unit tests have been provided that tests the new functionality.

2022-01-21 17:17 UTC, jasonjkeller requested changes

2022-01-21 17:17 UTC, jasonjkeller commented on instrumentation/apache-log4j-1/src/main/java/com/nr/agent/instrumentation/log4j1/Logger_Instrumentation.java
> +public class Logger_Instrumentation {
Class name should match the name of the class being weaved, so we'll want to change this to `Category_Instrumentation`

2022-01-21 17:17 UTC, jasonjkeller commented on instrumentation/apache-log4j-1/src/test/java/com/nr/agent/instrumentation/log4j1/Logger_InstrumentationTest.java
> +public class Logger_InstrumentationTest {
Should also be refactored to `Category_InstrumentationTest`

2022-01-24 10:40 UTC, danybmx commented
Hi @jasonjkeller, thanks for the feedback! changes done in c0a3ff2

2022-01-24 18:02 UTC, jasonjkeller approved these changes

2022-01-24 18:04 UTC, merged